# Level 2 - Task 3

## Feature Engineering

### Objective

Extract additional features from existing columns and create new encoded features for machine learning and analysis.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("Dataset .csv")

df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [3]:
df = df.dropna(subset=['Cuisines'])

print(df.shape)

(9542, 21)

In [4]:
df["Restaurant Name Length"] = df["Restaurant Name"].str.len()

df[["Restaurant Name","Restaurant Name Length"]].head()

          Restaurant Name  Restaurant Name Length
0        Le Petit Souffle                      16
1        Izakaya Kikufuji                      16
2  Heat - Edsa Shangri-La                      22
3                    Ooma                       4
4             Sambo Kojin                      11

In [5]:
df["Address Length"] = df["Address"].str.len()

df[["Address","Address Length"]].head()

                                             Address  Address Length
0  Third Floor, Century City Mall, Kalayaan Avenu...              71
1  Little Tokyo, 2277 Chino Roces Avenue, Legaspi...              67
2  Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...              56
3  Third Floor, Mega Fashion Hall, SM Megamall, O...              70
4  Third Floor, Mega Atrium, SM Megamall, Ortigas...              64

In [6]:
df["Table Booking Encoded"] = (
    df["Has Table booking"]
    .map({"Yes":1,"No":0})
)

df[
    ["Has Table booking",
     "Table Booking Encoded"]
].head()

  Has Table booking  Table Booking Encoded
0               Yes                      1
1               Yes                      1
2               Yes                      1
3                No                      0
4               Yes                      1

In [7]:
df["Online Delivery Encoded"] = (
    df["Has Online delivery"]
    .map({"Yes":1,"No":0})
)

df[
    ["Has Online delivery",
     "Online Delivery Encoded"]
].head()

  Has Online delivery  Online Delivery Encoded
0                  No                        0
1                  No                        0
2                  No                        0
3                  No                        0
4                  No                        0

In [8]:
new_features = [
    "Restaurant Name Length",
    "Address Length",
    "Table Booking Encoded",
    "Online Delivery Encoded"
]

df[new_features].head()

,Restaurant Name Length,Address Length,Table Booking Encoded,Online Delivery Encoded
0,16,71,1,0
1,16,67,1,0
2,22,56,1,0
3,4,70,0,0
4,11,64,1,0

In [9]:
print(df[new_features].describe())

       Restaurant Name Length  Address Length  Table Booking Encoded  \
count             9542.000000     9542.000000            9542.000000
mean                15.162649       53.553134               0.121358
std                  6.858410       17.121178               0.326560
min                  2.000000       13.000000               0.000000
25%                 10.000000       41.000000               0.000000
50%                 14.000000       52.000000               0.000000
75%                 19.000000       64.000000               0.000000
max                 54.000000      132.000000               1.000000

       Online Delivery Encoded
count              9542.000000
mean                  0.256864
std                   0.436927
min                   0.000000
25%                   0.000000
50%                   0.000000
75%                   1.000000
max                   1.000000